apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ping-monitor.fullname" . }}
  labels:
    {{- include "ping-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ping-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ping-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CHECK_INTERVAL
          value: "{{ .Values.env.CHECK_INTERVAL }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
