services:
  ping-monitor:
    build: ./app
    container_name: ping-monitor
    volumes:
      - ./logs:/app/logs
      - ./app/hosts.txt:/app/hosts.txt
    environment:
      - CHECK_INTERVAL=30
      - TELEGRAM_TOKEN=8904638973:AAGXTE_35CpvcRgv3uUesFkKdEb1KFM6m6E
      - TELEGRAM_CHAT_ID=572022108
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grafana
    restart: unless-stopped

volumes:
  grafana_data:
